service: sns-lambda-kinesis-sandbox

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  postSnsMessage:
    handler: handler.postSnsMessage
    events:
      - http:
          path: message
          method: post

  snsParse:
    handler: handler.snsParse
    events:
      - sns: snsSandbox

  kinesisParse:
    handler: handler.kinesisParse
    events:
      - stream:
          arn: arn:aws:kinesis:us-east-1:264454411691:stream/String-Preprocess
          batchSize: 100

#    Define function environment variables here
#    environment:
#      variable2: value2
